const ContactTypes = {
  CONTACT_MESSAGE_START: "CONTACT_MESSAGE_START",
  CONTACT_MESSAGE_SUCCESS: "CONTACT_MESSAGE_SUCCESS",
  CONTACT_MESSAGE_FAIL: "CONTACT_MESSAGE_FAIL",
};
export default ContactTypes;
